1443563394335	Sync.Service	INFO	Loading Weave 1.43.0
1443563394338	Sync.Engine.Clients	DEBUG	Engine initialized
1443563394339	Sync.Engine.Clients	DEBUG	Resetting clients last sync time
1443563394347	Sync.Engine.Bookmarks	DEBUG	Engine initialized
1443563394352	Sync.Engine.Forms	DEBUG	Engine initialized
1443563394356	Sync.Engine.History	DEBUG	Engine initialized
1443563394361	Sync.Engine.Passwords	DEBUG	Engine initialized
1443563394366	Sync.Engine.Prefs	DEBUG	Engine initialized
1443563394370	Sync.Engine.Tabs	DEBUG	Engine initialized
1443563394371	Sync.Engine.Tabs	DEBUG	Resetting tabs last sync time
1443563394378	Sync.Engine.Addons	DEBUG	Engine initialized
1443563394380	Sync.Service	INFO	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
1443563394384	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1443563394386	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1443563394387	Sync.Service	DEBUG	Caching URLs under storage user base: https://sync-191-us-west-2.sync.services.mozilla.com/1.5/17789140/
1443563394387	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1443563394996	Sync.Engine.AdblockPlus	DEBUG	Engine initialized
1443563394998	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1443563396825	FirefoxAccounts	DEBUG	got keyPair
1443563396826	FirefoxAccounts	DEBUG	getCertificateSigned: true true
1443563398999	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1443563399000	Sync.Service	DEBUG	User-Agent: Firefox/41.0 FxSync/1.43.0.20150923050452.
1443563399001	Sync.Service	INFO	Starting sync at 2015-09-29 16:49:59
1443563399001	Sync.Service	DEBUG	In sync: should login.
1443563399002	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1443563399002	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1443563476922	Hawk	WARN	hawk request error: [Exception... "NS_ERROR_UNKNOWN_HOST"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465"  data: no] Stack trace: onStopRequest()@resource://services-common/rest.js:465 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476925	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < _onComplete()@resource://services-common/hawkclient.js:215 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476927	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 659"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:659 < _onComplete()@resource://services-common/hawkclient.js:218 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476927	Hawk	DEBUG	(Response) /certificate/sign: code: null - Status text: null
1443563476928	Sync.RESTResponse	TRACE	Processing response headers.
1443563476928	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:311 < _onComplete()@resource://services-common/hawkclient.js:225 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476929	Sync.RESTResponse	TRACE	Processing response headers.
1443563476929	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._maybeNotifyBackoff()@resource://services-common/hawkclient.js:311 < _onComplete()@resource://services-common/hawkclient.js:226 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476930	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status text:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatusText]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.statusText :: line 659"  data: no] Stack trace: RESTResponse.prototype.statusText()@resource://services-common/rest.js:659 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:121 < _onComplete()@resource://services-common/hawkclient.js:231 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476931	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:122 < _onComplete()@resource://services-common/hawkclient.js:231 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476932	Sync.RESTResponse	DEBUG	Caught exception fetching HTTP status code:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.responseStatus]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.status :: line 643"  data: no] Stack trace: RESTResponse.prototype.status()@resource://services-common/rest.js:643 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:123 < _onComplete()@resource://services-common/hawkclient.js:231 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476932	Sync.RESTResponse	TRACE	Processing response headers.
1443563476933	Sync.RESTResponse	DEBUG	Caught exception processing response headers:[Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIHttpChannel.visitResponseHeaders]"  nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)"  location: "JS frame :: resource://services-common/rest.js :: RESTResponse.prototype.headers :: line 693"  data: no] Stack trace: RESTResponse.prototype.headers()@resource://services-common/rest.js:693 < this.HawkClient.prototype._constructError()@resource://services-common/hawkclient.js:128 < _onComplete()@resource://services-common/hawkclient.js:231 < onComplete()@resource://services-common/hawkclient.js:272 < onStopRequest()@resource://services-common/rest.js:467 < waitForSyncCallback()@resource://services-common/async.js:102 < makeSpinningCallback/callback.wait()@resource://services-common/async.js:145 < onNotify()@resource://gre/modules/services-sync/service.js:1000 < WrappedNotify()@resource://services-sync/util.js:148 < WrappedLock()@resource://services-sync/util.js:103 < WrappedCatch()@resource://services-sync/util.js:77 < login()@resource://gre/modules/services-sync/service.js:1022 < sync/<()@resource://gre/modules/services-sync/service.js:1272 < WrappedCatch()@resource://services-sync/util.js:77 < sync()@resource://gre/modules/services-sync/service.js:1268 < <file:unknown>
1443563476933	FirefoxAccounts	ERROR	error POSTing /certificate/sign: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1443563476934	FirefoxAccounts	ERROR	HAWK.signCertificate error: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1443563476934	Sync.BrowserIDManager	ERROR	Non-authentication error in _fetchTokenForUser: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1443563476934	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1443563476934	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1443563476937	Sync.BrowserIDManager	ERROR	Background fetch for key bundle failed: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1443563476938	Sync.BrowserIDManager	ERROR	Could not authenticate: {"error":{},"errorString":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 465\"  data: no]","message":null,"code":null,"errno":null}
1443563476939	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1443563476939	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms.
1443563476940	Sync.ErrorHandler	ERROR	Sync encountered a login error
